# Generated by Django 5.2.7 on 2025-11-02 08:29

import django.db.models.deletion
import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_link_event_instagram_link_event_reg_link_and_more'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text Only'), ('image', 'Image'), ('video', 'Video'), ('mixed', 'Mixed Content')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='tagged_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_posts', to='event.event'),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, help_text='Supported formats: MP4, MOV, AVI, WMV', null=True, upload_to='post_videos/', validators=[post.models.validate_video_extension]),
        ),
    ]
